#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)";ENV_FILE="$ROOT_DIR/.env";MIGRATION_DIR="$ROOT_DIR/backend/migrations"
read_env(){ awk -F= -v key="$1" '$0 !~ /^[[:space:]]*#/ && $1==key {value=substr($0,index($0,"=")+1);gsub(/^[[:space:]]+|[[:space:]]+$/,"",value);gsub(/^["\047]|["\047]$/,"",value);print value;exit}' "$ENV_FILE"; }
load_key(){ local key="$1" parsed;[ -n "${!key-}" ]&&return 0;[ -f "$ENV_FILE" ]||return 0;parsed="$(read_env "$key")";[ -z "$parsed" ]||export "$key=$parsed"; }
for key in DATABASE_URL JWT_SECRET GOVERNANCE_TENANT_ID ENABLE_GENERATED_FEATURES ALLOW_SCHEMA_MIGRATION BACKEND_PORT FRONTEND_PORT OPENROUTER_API_KEY OPENROUTER_MODEL OPENROUTER_BASE_URL PROVISION_ADMIN_EMAIL PROVISION_ADMIN_PASSWORD BOOTSTRAP_ACKNOWLEDGEMENT;do load_key "$key";done
if command -v pyenv >/dev/null 2>&1;then PYTHON_BIN="${PYTHON_BIN:-$(pyenv which python3)}";else PYTHON_BIN="${PYTHON_BIN:-python3}";fi
fail(){ printf 'error: %s\n' "$*" >&2;exit 1; }
port_free(){ if command -v lsof >/dev/null 2>&1&&lsof -tiTCP:"$1" -sTCP:LISTEN >/dev/null 2>&1;then fail "port $1 is already in use; refusing to terminate another process";fi; }
check(){ local secret="${JWT_SECRET:-}";command -v "$PYTHON_BIN" >/dev/null||fail "python3 is required";[ -n "${DATABASE_URL:-}" ]||fail "DATABASE_URL is required";[ -n "${GOVERNANCE_TENANT_ID:-}" ]||fail "GOVERNANCE_TENANT_ID is required";[ "${#secret}" -ge 32 ]||fail "JWT_SECRET must contain at least 32 characters";[ "${ENABLE_GENERATED_FEATURES:-false}" != true ]||[ "${APP_ENV:-development}" != production ]||fail "generated features are forbidden in production";printf 'configuration valid for tenant %s\n' "$GOVERNANCE_TENANT_ID"; }
migrate(){ check;[ "${ALLOW_SCHEMA_MIGRATION:-0}" = 1 ]||fail "set ALLOW_SCHEMA_MIGRATION=1";command -v psql >/dev/null||fail "psql is required";for f in "$MIGRATION_DIR"/*.sql;do psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f "$f";done; }
start(){ local api_port="${BACKEND_PORT:-${PORT:?PORT or BACKEND_PORT is required}}" ui_port="${FRONTEND_PORT:?FRONTEND_PORT is required}";check;[ "$api_port" != "$ui_port" ]||fail "backend and frontend ports must differ";[ -n "${OPENROUTER_API_KEY:-}" ]||fail "OPENROUTER_API_KEY is required";[ -n "${OPENROUTER_MODEL:-}" ]||fail "OPENROUTER_MODEL is required";[ "${OPENROUTER_BASE_URL:-}" = "https://openrouter.ai/api/v1" ]||fail "canonical OPENROUTER_BASE_URL is required";[ "${ALLOW_SCHEMA_MIGRATION:-}" = true ]||fail "ALLOW_SCHEMA_MIGRATION=true is required";[ -d "$ROOT_DIR/frontend/node_modules" ]||fail "frontend dependencies are missing; install explicitly";port_free "$api_port";port_free "$ui_port";"$PYTHON_BIN" "$ROOT_DIR/backend/scripts/prepare_runtime.py";export ALLOWED_ORIGINS="${ALLOWED_ORIGINS:-http://${FRONTEND_HOST:-127.0.0.1}:$ui_port}";(cd "$ROOT_DIR"&&"$PYTHON_BIN" -m uvicorn backend.app.main:app --host "${BACKEND_HOST:-127.0.0.1}" --port "$api_port")&api_pid=$!;(cd "$ROOT_DIR/frontend"&&VITE_BACKEND_PORT="$api_port" VITE_FRONT_PORT="$ui_port" npm run dev -- --host "${FRONTEND_HOST:-127.0.0.1}" --port "$ui_port" --strictPort)&ui_pid=$!;trap 'kill "$api_pid" "$ui_pid" 2>/dev/null||true;wait "$api_pid" "$ui_pid" 2>/dev/null||true' INT TERM EXIT;wait "$api_pid" "$ui_pid"; }
case "${1:-start}" in check)check;;migrate)migrate;;start)start;;*)fail "usage: $0 {check|migrate|start}";;esac
